### PR TITLE
Document Kubie usage

### PR DESCRIPTION
**Pull request by yasn77**
In preparation for `gsctl` release with kubie option, document how it can be
used.

Related to PR https://github.com/giantswarm/gsctl/pull/608

### Please remember to

- [x] Give the PR a meaningful title -- it will be shown in the release notes
- [x] Add (or remove) [user questions](https://github.com/giantswarm/docs/blob/master/CONTRIBUTING.md#front-matter) associated with any updated docs

### CODE REVIEW

**Comment by marians** [comment]
@yasn77 I installed kubie and tried the following:

```
# (build from gsctl master)

$ ./gsctl select endpoint gollum
Endpoint selected: https://api.g8s.gollum....

$ ./gsctl create kubeconfig --ttl 2h --kubie -c c68pn
New key pair created with ID 294bff3da… and expiry of 2 hours

Launching kubie with following context:

    giantswarm-c68pn

Darwin Marians-MacBook-Pro.local 20.3.0 x86_64
 9:28  up 12 days,  2:12, 8 users, load averages: 18.83 6.44 4.08

> k get nodes
Error in configuration:
* unable to read client-cert /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.crt for giantswarm-c68pn-user due to open /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.crt: no such file or directory
* unable to read client-key /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.key for giantswarm-c68pn-user due to open /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.key: no such file or directory
```

Indeed the files don't exist.

**Comment by yasn77** [comment]
> @yasn77 I installed kubie and tried the following:
> 
> ```
> # (build from gsctl master)
> 
> $ ./gsctl select endpoint gollum
> Endpoint selected: https://api.g8s.gollum....
> 
> $ ./gsctl create kubeconfig --ttl 2h --kubie -c c68pn
> New key pair created with ID 294bff3da… and expiry of 2 hours
> 
> Launching kubie with following context:
> 
>     giantswarm-c68pn
> 
> Darwin Marians-MacBook-Pro.local 20.3.0 x86_64
>  9:28  up 12 days,  2:12, 8 users, load averages: 18.83 6.44 4.08
> 
> > k get nodes
> Error in configuration:
> * unable to read client-cert /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.crt for giantswarm-c68pn-user due to open /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.crt: no such file or directory
> * unable to read client-key /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.key for giantswarm-c68pn-user due to open /Users/marian/.config/gsctl/certs/c68pn-66da8a198a-client.key: no such file or directory
> ```
> 
> Indeed the files don't exist.

I've had a similar problem before and it was a legitimate problem with kubeconfig. Like you found the keypair doesn't exist but it's referenced in kubeconfig.

I think introducing kubie has exposed a different issue. When I looked into this in the past, I remember it being related to a change in kubectl behaviour.

So imho, it's not something that should stop merging, since it's not an actual issue with the change, but potentially just exposing a different problem that isn't directly related. afaik in usual scenarios, the user shouldn't get this... At least I haven't seen it n awhile :

**Comment by marians** [comment]
If somebody else can confirm that it works in the described way, I'd feel fine. Right now I can't.

**Comment by yasn77** [comment]
The thing is this would fail even for things like Helm or straight kubectl, as the error comes from `client-go`, not kubie:


https://github.com/kubernetes/client-go/blob/758467711e075d6fd3d31abcaf6e2e1eb51ef3d4/tools/clientcmd/validation.go#L281

I understand this may seem like something new, but it's not something unexpected, since any tool that uses `client-go` would have a similar issue. 

I am still unsure why the cert and key disappears and still trying to figure that out, but I don't think it should stop this useful feature from being released.

It would be good if someone else from @giantswarm/sig-ux can give it a go and see if it works for them

**Review by marians — APPROVED** [review]
Meanwhile gsctl works as explained. Thanks for the addition!

I just created a gsctl release, so this PR can be merged as soon as you like @yasn77

**Pull request merged**
