### PR TITLE
Add first bits of the App Tutorial 

### PR DESCRIPTION
**Pull request by pipo02mix**
These is a  detailed the guide to build your own catalog of applications leveraging on App Platform. We will explain the reasons and the way the App Platform is built and how you can use to remove some burden when you need to ensure all clusters must have running a  set of Applications.﻿

### CODE REVIEW

**Comment by marians** [comment]
@pipo02mix Do you think it's likely that this will be completed any time soon? I'd like to reduce the number of open PRs in docs a bit.

**Comment by pipo02mix** [comment]
I have just written the outline, the idea was @ced0ps adds the content. IMO it has a great purpose and I would continue with it, but up to @giantswarm/team-halo to decide

**Comment by ubergesundheit** [comment]
Lets keep it at least until @ced0ps is back.

I like the direction and the content already present.

**Comment by marians** [comment]
⚠️  Watch out! This repository's default branch has changed and is now `main`.

You can update your local clone using these commands:

```nohighlight
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by pipo02mix** [comment]
Closing this because we are not working on it

**Pull request closed without merging**
