### PR TITLE
Add kvm documentation for automatic bad node termination

### PR DESCRIPTION
**Pull request by yulianedyalkova**
Towards https://github.com/giantswarm/roadmap/issues/176

We also need to update the release version once https://github.com/giantswarm/kvm-operator/commit/8bb78861c3847feb483d1b542acdec755d1c355b gets released.

### CODE REVIEW

**Review by marians — CHANGES_REQUESTED** [review]
If the feature is available for KVM, the `platform_support_table` in line 13 must be updated.

Since the annotation suggests that this is an alpha feature, it should look like `kvm="alpha=vX.Y.Z"`, where `X.Y.Z` has to be the actual release version introducing the feature.

Also the intro text (line 19) should either be extended to cover KVM, or simplified (since it duplicates the platform_support_table content.

In addition, please only merge this PR once the KVM release bringing this feature is actually active. Thanks!

**Review by tfussell — APPROVED** [review]
The content is good. I'm happy with it once Marian's comments are addressed.

**Comment by marians** [comment]
Heads-up: https://github.com/giantswarm/docs/pull/778 is going to be merged soon. The guide you are editing is moving to `/advanced/automatic-node-termination/`.

See https://docs-staging.c68pn.k8s.gollum.westeurope.azure.gigantic.io/advanced/automatic-node-termination/ for a staging version.

With that PR we also changed the way we link to other docs pages. Please check the `relref` documentation here: https://github.com/giantswarm/docs/blob/content-restructuring/CONTRIBUTING.md#hyperlinks

Pages you are linking have moved.

- `/reference/cp-k8s-api/kvmconfigs.provider.giantswarm.io/` is now `/ui-api/management-api/crd/kvmconfigs.provider.giantswarm.io/`
- `/basics/api/#cp-k8s-api` is now `/ui-api/management-api/` or `/ui-api/management-api/overview/`

**Review by mazzy89 — APPROVED** [review]

**Comment by yulianedyalkova** [comment]
@marians thanks for the feedback, I finally applied it since the feature will finally come out with [v14.0.0](https://github.com/giantswarm/releases/pull/551). 

Just one question about this:
>Since the annotation suggests that this is an alpha feature, it should look like kvm="alpha=vX.Y.Z", where X.Y.Z has to be the actual release version introducing the feature.

Should it be `alpha` or `ga`? I noticed that aws and azure have been `ga` since the beginning and I'm not quite sure what the difference is.

**Comment by marians** [comment]
> Should it be `alpha` or `ga`? I noticed that aws and azure have been `ga` since the beginning and I'm not quite sure what the difference is.

I'm pretty sure that's a mistake. On AWS, [automatic termination of bad nodes](https://docs.giantswarm.io/advanced/automatic-node-termination/) is still an alpha feature, right @alex-dabija ? And what stage is it on Azure actually?

**Review by marians — APPROVED** [review]
Approving to unblock this.

**Comment by alex-dabija** [comment]
On AWS the feature is alpha, but it will be promoted to GA and enabled by default in our next release v15.0.0 .

**Comment by alex-dabija** [comment]
On Azure the feature is not enabled by default. I would consider it alpha for now until it's actually enabled for more clusters.

**Comment by alex-dabija** [comment]
Also, the annotation has alpha in it's name: `alpha.node.giantswarm.io/terminate-unhealthy` .

**Comment by marians** [comment]
Thanks @alex-dabija for clarifying! Can you please make sure that the info is fixed in docs?

**Comment by alex-dabija** [comment]
> Thanks @alex-dabija for clarifying! Can you please make sure that the info is fixed in docs?

Yes, I'm looking into it now.

**Comment by alex-dabija** [comment]
I will update the docs in a separate PR after this one is merged.

**Pull request merged**
