### PR TITLE
Drop "Policy" suffix from names ; Drop ARN part

### PR DESCRIPTION
**Pull request by kopiczko**
- "GiantSwarmAWSOperator" is the policy name we currently have in all
  our CP accounts.
- ARNs are predictable - no need to copy them. The important bit is that
  we have roles named consistently.

### CODE REVIEW

**Review by corest — APPROVED** [review]

**Comment by marians** [comment]
Can't judge here. Deferring to @paurosello .

**Comment by marians** [comment]
@paurosello Is this fine with you?

**Review by paurosello — APPROVED** [review]
Yes, the terraform modules were updated and customer notifications have been sent already :)

**Comment by kopiczko** [comment]
Going with that. There will be another PR comming because now we setup CP/TC accounts the same way.

**Pull request merged**
