### PR TITLE
Add Loki to changes

### PR DESCRIPTION
**Pull request by cokiengchiara**

### CODE REVIEW

**Comment by cokiengchiara** [comment]
@marians is off I don't really know who else could approve this. But it's simple like this prevoius PR https://github.com/giantswarm/docs/pull/728

@MartaD I think it's fine to announce linking to github and not to our docs site...

**Review by marians — APPROVED** [review]

**Comment by marians** [comment]
I'm not off :)

**Comment by marians** [comment]
@cokiengchiara Is this one ready?

**Comment by cokiengchiara** [comment]
> I'm not off :)

I thought you were off for hahaha Nudeln vom Asiatisch

**Pull request merged**
