### PR TITLE
Add health reference page

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/roadmap/issues/13

This PR is supposed to add a reference page on cluster health under the path

    /reference/health/

### TODO

- [ ] Review rules for correctness

### CODE REVIEW

**Comment by oponder** [comment]
Is this still relevant?

**Comment by marians** [comment]
The story is in @giantswarm/team-ludacris 's hands, but parked (AFAIK). Let's ask whether they want to have this PR around.

**Comment by MarcelMue** [comment]
We will not get to this any time soon - we can keep the PR around though.

**Comment by marians** [comment]
As it's getting less and less likely that the story will get implemented as described here, and as I am constantly stumbling upon this, I'm closing the PR.

**Pull request closed without merging**
