### PR TITLE
Document CRD annotations

### PR DESCRIPTION
**Pull request by paurosello**
Towards https://github.com/giantswarm/giantswarm/issues/14222

### Please remember to

- [x] Give the PR a meaningful title -- it will be shown in the release notes
- [ ] Add (or remove) [user questions](https://github.com/giantswarm/docs/blob/master/CONTRIBUTING.md#front-matter) associated with any updated docs

### CODE REVIEW

**Comment by paurosello** [comment]
CRD aannotation example:

image

**Review by calvix — APPROVED** [review]

**Comment by marians** [comment]
Please execute `make update-crd-reference` to re-generate the CRD reference pages.

**Comment by marians** [comment]
Note that you also have to update the `crd.template` file in https://github.com/giantswarm/docs/blob/master/scripts/update-crd-reference/crd.template

**Review by marians — CHANGES_REQUESTED** [review]
See my comments before

**Comment by paurosello** [comment]
ahhh thanks! was debugging why the CRDs were not correctly generated :)

**Review by marians — APPROVED** [review]
Awesome!

**Pull request merged**
