### PR TITLE
Ignore deprecated CRDs

### PR DESCRIPTION
**Pull request by MartaD**
Adding CRDs to this list will omit them when docs are generated

### CODE REVIEW

**Review by stone-z — APPROVED** [review]
LGTM but just to double check -- are the names singular like this? It might be `drainerconfigs`?

**Comment by MarcelMue** [comment]
I think it should be:
```
drainerconfigs.core.giantswarm.io
storageconfigs.core.giantswarm.io
```

**Comment by MartaD** [comment]
How can I test it? Do I need to test it?

**Review by stone-z — APPROVED** [review]
That looks better to me

**Review by whites11 — APPROVED** [review]

**Pull request merged**
