### PR TITLE
Add base for documentation for Zot

### PR DESCRIPTION
**Pull request by uvegla**
### What this PR does / why we need it

Documentation on some generic in-cluster registry mirroring and the GS approach for it with Zot, extended with some Zot use cases and configurations for certain scenarios.

### CODE REVIEW

**Comment by pipo02mix** [comment]
I would vote for adding to new Tutorials folder :)

I plan to do the menu switch soonish (once other pending PRs are approved)

**Comment by pipo02mix** [comment]
This is the designed tree for Tutorials 

Screenshot 2024-07-12 at 11 31 30

[source](https://miro.com/app/board/uXjVO2Dh15w=/)

I am not completely sure where we can add it, any suggestion? do we need a new section?

**Review by marians — APPROVED** [review]

**Comment by uvegla** [comment]
@pipo02mix Moved under tutorials. Decided to create a new section. Is it correct this way?

**Review by pipo02mix — APPROVED** [review]
I took the freedom to fix vale warnings

**Comment by uvegla** [comment]
Thanks a lot @pipo02mix! ❤️

**Pull request merged**
