### PR TITLE
Add Azure releases to docs

### PR DESCRIPTION
**Pull request by yulianedyalkova**
### What this PR does / why we need it

Now that we have release [v25.0.0](https://github.com/giantswarm/releases/tree/master/azure/v25.0.0) for Azure, we also need to start generating docs for it.

### Things to check/remember before submitting

- If you made content changes

    - Run `make lint dev` to render and proofread content changes locally.
    - Bump `last_review_date` in the front matter header if you reviewed the entire page.

### CODE REVIEW

**Review by njuettner — APPROVED** [review]

**Review by T-Kukawka — APPROVED** [review]

**Comment by T-Kukawka** [comment]
cc @pipo02mix

**Comment by pipo02mix** [comment]
wait, but is this CAPZ? Why don't we name the folder `capz`? That way, we follow the convention `capa`, `capv`,...

**Comment by pipo02mix** [comment]
@yulianedyalkova ?

**Comment by yulianedyalkova** [comment]
@pipo02mix I was afk :) The longterm plan is to use the names of the providers rather than capa/capz/etc. CAPA was used because of conflicts with vintage but even there we want to eventually go back to just using aws.

**Comment by pipo02mix** [comment]
and what happens with AKS and pure Azure? or aws and eks?

**Comment by yulianedyalkova** [comment]
That is a conversation that started in [this rfc](https://github.com/giantswarm/rfc/pull/86) but there is no final decision yet. Azure vs capz is certain though as capz is just an implementational detail that shouldn't reach customers. So can we move forward with this PR as it's currently blocking us from announcing the azure releases we already have out?

**Review by marians — APPROVED** [review]

**Pull request merged**
