### PR TITLE
Office hour teaser for April

### PR DESCRIPTION
**Pull request by Oshratn**
Towards giantswarm/giantswarm#15720

This replaces the textual office hours link with a graphical banner.

The block only renders until April 7, 2021, to avoid us forgetting about outdated content.

### Please remember to

- [x] Give the PR a meaningful title -- it will be shown in the release notes
- [ ] Add (or remove) [user questions](https://github.com/giantswarm/docs/blob/master/CONTRIBUTING.md#front-matter) associated with any updated docs

### CODE REVIEW

**Review by marians — APPROVED** [review]
Awesome, this will work!

Can you please also delete the `2021-04-office-hours.jpg` file? Thanks!

**Comment by Oshratn** [comment]
Delete the April file `2021-04-office-hours.jpg` or the March one?

**Comment by marians** [comment]
Sorry for the confusion. I meant to delete the old one, as it is no longer needed.

**Comment by marians** [comment]
Done

**Pull request merged**
