### PR TITLE
Add new version AWS platform

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/10443

### CODE REVIEW

**Comment by marians** [comment]
@pipo02mix The JPEG format is not ideal for graphics like these, it's made for photographic images. Do you still have the master files of them, so we could export them as PNGs?

**Comment by pipo02mix** [comment]
- [AWS control plane](https://docs.google.com/drawings/d/1OFZNopT7PKUBnVKmPK8FllAy1cHxvHUtGyo2pjHmqZE/edit?usp=sharing)
- [Security layers](https://docs.google.com/drawings/d/1PaiVvbZyDyQMEJ3389g7GXgZyHUvJ_x8bvdcrM7WCQU/edit?usp=sharing)
- [Tenant cluster](https://docs.google.com/drawings/d/1PHhl5DxfQkM9-H2U0lkfIb8406mbCBW73IWbI-8MN7E/edit?usp=sharing)

Should I use svg?

**Comment by Oshratn** [comment]
LGTM from the words perspective

**Comment by marians** [comment]
Took the liberty to commit directly into this branch

- Replaced JPEG with PNG
- Changed some headline formatting and white space

**Pull request merged**
