### PR TITLE
Dissolve reference section

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/giantswarm/issues/20188

This PR moved the three pages currently contained in the "Reference" top level section into other sections.

We want to make room on the top level and the reference section was one that didn't fulfil a real purpose.

### CODE REVIEW

**Comment by marians** [comment]
@giantswarm/team-rainbow As SIG Docs seems to be slacking, maybe you can help me out with a review? <3

**Review by kuosandys — APPROVED** [review]
Looks good to me 👍

**Comment by kuosandys** [comment]
Btw "Reference" still shows up in the side bar - just checking that we still want that to be there, right?

**Comment by marians** [comment]
No, good catch! I had missed that, also with the Kubernetes basics section.

**Pull request merged**
