### PR TITLE
CI: build site in Hugo, bring warnings to the PR as comment

### PR DESCRIPTION
**Pull request by marians**
If warnings are yielded on `hugo build`, they will be commented in the PR.

Preview:

image

If errors are found, they will fail the validate job.

### CODE REVIEW

**Comment by lyind** [comment]
Wish this could use the regular build process.

Unfortunately that runs on Circle CI, but maybe one could still access and parse the hugo build output from there?

**Comment by marians** [comment]
> Wish this could use the regular build process.
> 
> Unfortunately that runs on Circle CI, but maybe one could still access and parse the hugo build output from there?

Nut sure. But it would be a lot more complicated that way.

**Review by lyind — APPROVED** [review]
A bit of duplication, but for a good cause.

LGTM

**Comment by pipo02mix** [comment]
nice

**Pull request merged**
