### PR TITLE
Getting started review

### PR DESCRIPTION
**Pull request by carillan81**
### What does this PR do?

Review the content of the getting started section:
 - Reorder some topics
 - Bring some docs about observability and app platform to this section

### What does it look like?

Change of ordering, files moved and links fixed. No content has been reviewed.

### Any background context you can provide?

We have been working on a doc restructure to make it easier to consume and to communicate the idea of a developer platform.

### What is needed from the reviewers?

Check that the changes make sense

### Have you maintained the front matter?

No changes in content, just refactoring of files

### CODE REVIEW

**Comment by puja108** [comment]
Main menu sub-menu structure is not set up for the app platform folder. It's set up for "Deploying an app" but the others are missing it. Can you add the parent to the others? Just copy it over from the frontmatter from Deploying an app.

Screenshot 2022-12-13 at 11 01 34

**Comment by carillan81** [comment]
> Main menu sub-menu structure is not set up for the app platform folder. It's set up for "Deploying an app" but the others are missing it. Can you add the parent to the others? Just copy it over from the frontmatter from Deploying an app.
> 
> Screenshot 2022-12-13 at 11 01 34

fixed!

**Comment by pipo02mix** [comment]
why `shared installations` or `installations names` are still in Getting Started?

**Comment by carillan81** [comment]
> why `shared installations` or `installations names` are still in Getting Started?

we commented that I wasn't moving them to support so I don't mess with other PR's. This should be moved in a "support reorg" PR

**Review by puja108 — APPROVED** [review]

**Comment by pipo02mix** [comment]
but I already moved in my PR 🤔 
Screenshot 2022-12-13 at 13 44 59

**Comment by carillan81** [comment]
> but I already moved in my PR thinking Screenshot 2022-12-13 at 13 44 59

maybe you haven't updated. It's correct in my code. :shrug:

**Comment by pipo02mix** [comment]
ah ok cool I saw wrong structure in old screenshot. All good then

**Pull request merged**
