### PR TITLE
Update 'kgs template nodepool' flag syntax to account for flag renaming (--nodes-min, --nodes-max)

### PR DESCRIPTION
**Pull request by marians**
Docs adaptation for https://github.com/giantswarm/kubectl-gs/pull/212

### CODE REVIEW

**Review by axbarsan — APPROVED** [review]

**Comment by marians** [comment]
Waiting for kubectl-gs release

**Comment by marians** [comment]
@axbarsan Any idea how long it usually takes for a release to appear in the krew index?

**Comment by marians** [comment]
@axbarsan Actually I don't see a PR appearing in https://github.com/kubernetes-sigs/krew-index/pulls?q=is%3Apr+ - is our automation not working?

**Comment by axbarsan** [comment]
> @axbarsan Actually I don't see a PR appearing in [https://github.com/kubernetes-sigs/krew-index/pulls?q=is%3Apr+](https://github.com/kubernetes-sigs/krew-index/pulls?q=is%3Apr+sort%3Aupdated-desc) - is our automation not working?

The krew-index CI task has to be approved manually, as mentioned [here](https://github.com/giantswarm/kubectl-gs/blob/master/docs/Release.md). I approved it now.

**Comment by marians** [comment]
Thanks! Somehow I didn't think I could find the answer somewhere in docs...

**Pull request merged**
