### PR TITLE
Update ingress api versions and annotation for nginx ingress controller

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR updates the api versions of examples regarding ingress and changes an annotation.

Related: https://gigantic.slack.com/archives/C13MG9F0W/p1600735827002400

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM from the report on slack. I am no Ingress wizard though.

**Comment by tfussell** [comment]
I apologize @ubergesundheit. When I was looking at it yesterday it seemed like it had been `v1` for a while, but now I see that it was only promoted to GA in 1.19. We should still update the docs, but we need to get 1.19 released on our platforms first. I think the other change is useful and correct. Maybe we could add a note about the pre-1.19 and post-1.19 method or just wait until 1.19 is ready to merge this.

**Comment by ubergesundheit** [comment]
Switched to `networking.k8s.io/v1beta1` which seems to be the version available until 1.22

**Review by tfussell — APPROVED** [review]
Sorry for the trouble. LGTM.

**Pull request merged**
