### PR TITLE
Added questions to metadata

### PR DESCRIPTION
**Pull request by Oshratn**
Towards #13270
Also changed to American spelling, as is the standard at GS.
Question: How does the difference in American and British spelling affect search?

### CODE REVIEW

**Review by ubergesundheit — APPROVED** [review]
LGTM. No Idea on search

**Comment by marians** [comment]
> Question: How does the difference in American and British spelling affect search?

It does affect search results in fact. For example, try https://docs.giantswarm.io/search/?q=organisation vs. https://docs.giantswarm.io/search/?q=organization

**Comment by Oshratn** [comment]
So.. should in cases with UK and US spelling, should there be 2 questions in the front matter?

**Comment by marians** [comment]
> So...in cases with UK and US spelling, should there be 2 questions in the front matter?

No, I think that would be the wrong way to handle this. Let's dig into technical ways to solve this, at some point. I'll create a new issue.

**Comment by marians** [comment]
@Oshratn I think this is ready to merge

**Pull request merged**
