### PR TITLE
Add highlights for 2023-01-12

### PR DESCRIPTION
**Pull request by marians**
### What does this PR do?

Add the weekly highlights

Please add your contributions as commits or suggestions by 14:00 CET today.

### CODE REVIEW

**Comment by uvegla** [comment]
I will add some flux related updated in a moment. Please don't release this yet.

**Comment by uvegla** [comment]
> I will add some flux related updated in a moment. Please don't release this yet.

Done, thanks!

**Comment by gianfranco-l** [comment]
@marians @puja108 @weatherhog @TheoBrigitte 
hi! weekly highlights have been paused for the past 2 weeks, I was wondering couple of things:
- when restarted shall we include all the past communications into one? 
- when restarted, can we use this PR (just editing the time in titles and metadata) since it has already quite some content?
- when the weekly highlights usually get restarted after christmas break (to try to catch as much customers' eyes as possible back from vacations), before / after jan 6th?

**Comment by marians** [comment]
@gianfranco-l Sorry, I was a bit overwhelmed with notifications and just saw your questions.

I changed this PR to contain the notifications for today. Would be great if all teams could add their contributions and check whether the mentioned ones are all important enough.

**Comment by gianfranco-l** [comment]
Nothing else to add to this week's highlights from honeybadger

**Review by weatherhog — APPROVED** [review]
Go for it

**Pull request merged**
