### PR TITLE
contribution kgs add base for weekly highlights

### PR DESCRIPTION
**Pull request by gianfranco-l**
Contribution about gitops add base command for weekly highlights

### CODE REVIEW

**Comment by uvegla** [comment]
It looks good to me, but I think the docs needs to be updated because of: https://github.com/giantswarm/kubectl-gs/blob/main/CHANGELOG.md#2310---2023-01-18 the folder structure was slightly changed. (Also might want to link this too.)

**Comment by gianfranco-l** [comment]
@carillan81 every week we create a list of highlights related to updates to docs, user interfaces and managed apps to our customers. This communication is sent out every thursday, in the early afteroon (Around 2 pm CET). About gitops add base command, do you think we can communicate this to customers already via this communication (that goes out to all customers Slack channels) or we need to hold on a bit until the change suggested by @uvegla is done and maybe postpone it for next week? Pls let me know :)

**Comment by carillan81** [comment]
I am working in the environments tutorial now, so we might wait and announce them together.

**Comment by gianfranco-l** [comment]
ok then, I'll remove the reference for gitops add base for this week, @carillan81 let us know once this piece of doc is ready to be announced

**Pull request closed without merging**
