### PR TITLE
Update spot instances doc to include azure

### PR DESCRIPTION
**Pull request by whites11**
Add references for spot instances on azure

### CODE REVIEW

**Comment by marians** [comment]
Heads-up: https://github.com/giantswarm/docs/pull/778 is going to be merged soon. The guide you are editing is moving to `/advanced/spot-instances/aws/`.

See https://docs-staging.c68pn.k8s.gollum.westeurope.azure.gigantic.io/advanced/spot-instances/aws/ for a staging version.

As the URL tells, that guide is thought to be for AWS. Would it make sense to add an Azure-specific guide next to it at `/advanced/spot-instances/azure/`?

I am thinking that the feature has quite some differences on AWS compared to Azure  (AWS: on-demand base capacity, spot percentage, Azure: pricing). That would justify a separate article.

If you like, we can discuss pros and cons in a call.

**Comment by whites11** [comment]
> Heads-up: #778 is going to be merged soon. The guide you are editing is moving to `/advanced/spot-instances/aws/`.
> 
> See https://docs-staging.c68pn.k8s.gollum.westeurope.azure.gigantic.io/advanced/spot-instances/aws/ for a staging version.
> 
> As the URL tells, that guide is thought to be for AWS. Would it make sense to add an Azure-specific guide next to it at `/advanced/spot-instances/azure/`?
> 
> I am thinking that the feature has quite some differences on AWS compared to Azure (AWS: on-demand base capacity, spot percentage, Azure: pricing). That would justify a separate article.
> 
> If you like, we can discuss pros and cons in a call.

makes sense to me to split.

**Comment by T-Kukawka** [comment]
@marians when is merged soon? :D as not sure how to proceed with this efficiently

**Comment by marians** [comment]
#778 is merged

**Comment by T-Kukawka** [comment]
i am creating new PR for this change - closing this one

**Pull request closed without merging**
