### PR TITLE
Replace SE term by AE

### PR DESCRIPTION
**Pull request by pipo02mix**
### Please remember to

- [x] Give the PR a meaningful title -- it will be shown in the release notes
- [ ] Add (or remove) [user questions](https://github.com/giantswarm/docs/blob/master/CONTRIBUTING.md#front-matter) associated with any updated docs

### CODE REVIEW

**Comment by marians** [comment]
Thanks for all the great work but, ... All changes under `/changes/` will be overwritten by automation.

**Comment by pipo02mix** [comment]
So what I do? I change it in the source (I guess releases repo)? or I leave it like it is?

**Comment by marians** [comment]
I think you don't have to go and change past releases and changelogs. (Yes, most of them would be in giantswarm/releases I guess.)

A `git checkout ./src/content/changes` might help to overwrite your changes.

**Comment by pipo02mix** [comment]
But can we just go ahead? you said it will be overwritten (so I don't need to revert commit and start again

(`git checkout ./src/content/changes` this not work)

**Comment by marians** [comment]
The correct command was `git checkout master -- src/content/changes`. I did it.

**Comment by pipo02mix** [comment]
nice TIL

**Review by marians — APPROVED** [review]

**Pull request merged**
