### PR TITLE
Add helm chart docs generator to create Cluster Apps section in reference

### PR DESCRIPTION
**Pull request by pipo02mix**
### What does this PR do?

(Please set a descriptive PR title. Use this space for additional explanations.)

Towards https://github.com/giantswarm/giantswarm/issues/29614

### What does it look like?

(If this is more than a textual change, a screenshot can help in some cases to speed up the review process.)

Screenshot 2024-02-09 at 13 33 42

### Any background context you can provide?

(Please link public issues or summarize if not public.)
We want to bring cluster apps to the docs

### Have you maintained the front matter?

(Please bump the last_review_date in case this qualifies as a review for an entire page. Provide user_questions which should be answered in the page. Provide a meaningful description.)

### CODE REVIEW

**Comment by marians** [comment]
It looks like there are two H1 headlines on the page. That shouldn't happen.

Also the headline

> cluster Cluster App configuration reference

is strange due to the repeated "cluster" and the first one being lowercase. Maybe it would help to wrap the name in backticks and use sentence case apart from that?

> `cluster` cluster app configuration reference

Or

> App configuration reference: `cluster`

Something I am missing in the top of the page is a link to the source repository.

**Comment by marians** [comment]
Something else: what is the content of the `Management API > Cluster apps` page?

**Comment by pipo02mix** [comment]
@marians PTAL

**Review by marians — APPROVED** [review]
Fine, let's iterate on improvements

**Pull request merged**
