### PR TITLE
Add metadata for CRDs used on AWS

### PR DESCRIPTION
**Pull request by marians**
This PR adds metadata which will be visible in the form of tags in the CRD listing. Example (before the change):

image

### CODE REVIEW

**Comment by calvix** [comment]
do we want to add this even when we only use the CRD for test purposes only and the customer is not exposed to it?

**Comment by marians** [comment]
@calvix The ones I am adding data for here are used in v20 and appear to any user who tries it. So I think they will be relevant soon enough. Antonia is also adding support for those to kubectl-gs via https://github.com/giantswarm/kubectl-gs/pull/380

**Comment by calvix** [comment]
but v20 is an internal release that should not available for customers and they should not try it :p

we do not run components that are responsible for v20 in other than our installations

**Comment by marians** [comment]
Closed, as these CRDs should rather be hidden

**Pull request closed without merging**
