### PR TITLE
Add highlights for the week ending 2022-02-04

### PR DESCRIPTION
**Pull request by marians**
Please add your content before February 4, 14:00 CET

### CODE REVIEW

**Comment by marians** [comment]
FYI @alex-dabija I have added an item regarding cgroupsv1 to the docs section. Let me know if you want to highlight that more and we can pull it to the top and change the wording.

**Comment by gianfranco-l** [comment]
opened [PR](https://github.com/giantswarm/docs/pull/1294) for honeybadger contribution to this week announcement @marians

**Comment by alex-dabija** [comment]
> FYI @alex-dabija I have added an item regarding cgroupsv1 to the docs section. Let me know if you want to highlight that more and we can pull it to the top and change the wording.

It's fine like this because we would prefer our customers to use cgroups v2 instead of v1.

**Comment by PrashantR31** [comment]
Nothing from Rainbow for this week.

**Comment by marians** [comment]
This just needs a final approval.

**Review by PrashantR31 — APPROVED** [review]
LGTM

**Pull request merged**
