### PR TITLE
OpenFaaS tutorial draft

### PR DESCRIPTION
**Pull request by marians**
A draft for a guide on how to get started with OpenFaaS.

Work In Progress

### CODE REVIEW

**Comment by puja108** [comment]
@marians I did a quick flyover this PR and it seems it would be ready to go, WDYT?

**Comment by alexellis** [comment]
@marians @puja108 feel free to ask for a technical review when you're ready to publish. Give us a few days notice.

Alex

**Comment by marians** [comment]
This has been a while since I touched it. I'd have to re-validate against latest versions. Also if I remember correctly I still had an open task regarding auto scaling.

Which reminds me that this would be a nice article to post once we have cluster autoscaling released.

@alexellis Thanks for the kind offer! And good job tracking community efforts! 👍

**Comment by tommyhobin** [comment]
Per our conversation. @rossf7 what do you think?

**Comment by alexellis** [comment]
Please feel free to hop into our Slack and get the conversation going. https://docs.openfaas.com/community - we'd like to see this post go out.

Something that I have to tell myself with drafts / never-ending blog-posts.. don't let perfect get in the way of good.

**Comment by rossf7** [comment]
@alexellis Thanks for the link and good point. We discussed in our content SIG meeting which is why there was some activity.

It's in my queue to review and see if I can help get it published.

**Pull request closed without merging**
